# Generated by Django 5.2.8 on 2026-02-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0004_add_question_reverse_and_thought_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalactivity',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or icon, e.g. 🚶 🌳 🏃', max_length=32),
        ),
        migrations.AddField(
            model_name='physicalactivity',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image URL for display'),
        ),
    ]
