# Generated by Django 6.0.1 on 2026-02-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0005_add_activity_image_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalactivity',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='Suggested duration in minutes (for timer)'),
        ),
    ]
