# Generated by Django 6.0.1 on 2026-02-01 19:32

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wellness', '0009_add_patient_doctor_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='Name of the test or examination', max_length=200)),
                ('result', models.TextField(help_text='Test results or findings')),
                ('treatment_plan', models.TextField(blank=True, help_text='Recommended treatment or next steps')),
                ('medical_notes', models.TextField(blank=True, help_text='Additional medical notes or observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_results', to='wellness.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Result',
                'verbose_name_plural': 'Medical Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
